apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: /policies
    apps.open-cluster-management.io/reconcile-rate: high
  name: multitenant-rbac
  namespace: acm-channels
spec:
  channel: acm-channels/multitenant-rbac
  placement:
    local: true