apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: rule-multitenant-rbac

spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: integrations-rbac, operator: In, values: ["yes"]}