apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-multitenant-rbac

placementRef:
  name: rule-multitenant-rbac
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io

subjects:
- name: multitenant-rbac
  kind: Policy
  apiGroup: policy.open-cluster-management.io