apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: multitenant-rbac-groups
  annotations:
    policy.open-cluster-management.io/categories: Securité infrastructure
    policy.open-cluster-management.io/controls: Configurations
    policy.open-cluster-management.io/standards: Configurations
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: multitenant-rbac-groups
        spec:
          remediationAction: inform
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:

                kind: Group
                apiVersion: user.openshift.io/v1
                metadata:
                  name: demo-rbac-developpeurs
                users:
                  - demo-rbac-dev

            - complianceType: musthave
              objectDefinition:

                kind: Group
                apiVersion: user.openshift.io/v1
                metadata:
                  name: demo-rbac-operations
                users:
                  - demo-rbac-ops

            - complianceType: musthave
              objectDefinition:

                kind: Group
                apiVersion: user.openshift.io/v1
                metadata:
                  name: demo-rbac-testeurs
                users:
                  - demo-rbac-tst