apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: multitenant-rbac-roles
  annotations:
    policy.open-cluster-management.io/categories: Securité infrastructure
    policy.open-cluster-management.io/controls: Configurations
    policy.open-cluster-management.io/standards: Configurations
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: multitenant-rbac-roles-dev
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            include: 
            - "integrations-dev"
          object-templates:
            - complianceType: musthave
              objectDefinition:

                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: demo-rback-binding-developpeurs-dev-admin
                subjects:
                  - kind: Group
                    name: demo-rbac-developpeurs
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: admin

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: multitenant-rbac-roles-prod
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            include: 
            - "integrations-prod"
          object-templates:
            - complianceType: musthave
              objectDefinition:

                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: demo-rback-binding-operations-prod-admin
                subjects:
                  - kind: Group
                    name: demo-rbac-operations
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: admin

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: multitenant-rbac-roles-preprod
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            include: 
            - "integrations-prod"
          object-templates:
            - complianceType: musthave
              objectDefinition:

                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: demo-rback-binding-testeurs-preprod-admin
                subjects:
                  - kind: Group
                    name: demo-rbac-operations
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: admin